#!/bin/bash

PASSES="-tensor-constant-bufferize \
-std-bufferize \
-tensor-bufferize \
-standalone-bufferize \
-linalg-bufferize \
-scf-bufferize \
-func-bufferize \
-finalizing-bufferize \
-buffer-hoisting \
-buffer-loop-hoisting \
-standalone-loop-hoisting \
-promote-buffers-to-stack \
-buffer-deallocation \
-canonicalize"
lagrad-opt "${1:-/dev/stdin}" $PASSES
